### ISSUE TITLE
menetrend.py és adat.py hiba

### ISSUE THREAD

**Issue by maxigaz** [b9nc9/menetrendek#1]
Szia!

Amikor futtatni akarom a menetrend.py és adat.py fájlokat, a következő hibakimeneteket kapom:

```
$ python menetrend.py
Traceback (most recent call last):
  File "menetrend.py", line 4, in <module>
    import volan
  File "/media/ext4part/home/xxx/Apps/menetrendek/volan.py", line 23
    print "[-]",
              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "[-]", end=" ")?
```

```
$ python adat.py
Traceback (most recent call last):
  File "adat.py", line 6, in <module>
    reload(sys)
NameError: name 'reload' is not defined
```

Mindkét esetben Python 3.6.4 van használva Manjaro Linux alatt.

**Comment by b9nc9** [comment]
Üdv!

Jelenleg csak Python 2-ben vannak megírva a szkriptek, de mivel látom, hogy igény van rá, így megírom 3-ban is. Ezt igyekszem minél hamarabb megtenni.

Köszönöm a visszajelzést!

**Comment by b9nc9** [comment]
A projektet átírtam az új verzióba, így ezt a verziót nem fejlesztem a továbbiakban.
Az új repo itt található: <https://github.com/b9nc9/volan>
Saját magam teszteltem az újat is, de ha esetleg problémák lépnek fel, akkor kérlek ott jelezd!

Köszönöm a türelmed!
